### ISSUE TITLE
Full resolution in deep zoom tiles

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/microscopy#10]
The users in CIRM place a high premium on being able to view images within the browser at highest resolution.  We need to look at what it would take to ensure that the highest level of zoom enables viewing of the actual data that came off the microscope.

**Comment by robes** [comment]
And to add to that. The tool we are using to convert from CZI to BigTIFF does some downsampling, if I remember correctly. It might be possible to change a setting on that tool so that it generates a full resolution BigTIFF (not sure). Alternatively, the longer term goal would be to consider converting the CZI directly.

**Comment by carlkesselman** [comment]
To start with, we should just figure out if we can do sample images using Zeiss tools.

**Comment by karlcz** [comment]
We now have our own czi2dzi conversion script that retains the whole pyramid.
