### ISSUE TITLE
Put color specifications into CZI converter script.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/microscopy#17]
Converter should place the following fields into the XML file in DZI

* NAME  — name of the channel, to be used in the channel selector. Used to pick default color if COLOR not otherwise specified.
* COLORALPHA — Value of Alpha channel. To default to 1 if not specified (although we need to make it  .9 for now until we fix the opacity value issue)  If the value coming in is FF for now we should clamp until .9 until we have the fix.
* COLORRGB  — Default color to start the channel at.

**Comment by karlcz** [comment]
This is implemented as CHANNELNAME, CHANNELALPHA, and CHANNELRGB. The color values are in normalized decimal floating point so 0.0 is minimum intensity and 1.0 is maximum intensity. The RGB string is whitespace separated component values e.g. "1.0 1.0 0.0" would be pure yellow.

I also added MINVALUE and MAXVALUE using the same normalized floating point format. These will always be a single number whether the channel is grayscale or interleaved samples, since you would want to retain ratios between interleaved samples even if rescaling the display range.

**Comment by meihuisu** [comment]
actually karlcz made it CHANNELDEFAULTRGB and CHANNELDEFAULTALPHA.

**Comment by meihuisu** [comment]
have updated the 2dviewer to process this. karlcz can confirm and close this

**Comment by karlcz** [comment]
The ImageProperties.xml has these fields depending on the input data:

- `minValue` and `maxValue` are normalized 0.0 to 1.0, i.e. 1.0 is max representable value in storage type
- `channelName`, e.g. `DAPI`, `TL Brightfield`, or `Alexa Fluor 488`
- `channelDefaultRGB` is a space-separated list of normalized values for red, green, and blue, e.g. `1.0 1.0 0.0` is yellow.
- `channelDefaultAlpha` is a normalized alpha opacity value, e.g. `1.0` is fully opaque
